version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,PLAINTEXT_HOST://localhost:19092
      - --schema-registry-addr=0.0.0.0:8081
    ports:
      - "9092:9092"
      - "9644:9644"
      - "19092:19092"
      - "8081:8081"
    networks:
      - redpanda-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:9092
      SCHEMAREGISTRY_ENABLED: "true"
      SCHEMAREGISTRY_URLS: "http://redpanda:8081"
    ports:
      - "8080:8080"
    networks:
      - redpanda-net
    depends_on:
      - redpanda

  okx-harvester:
    build:
      context: .                       # КОРЕНЬ репозитория!
      dockerfile: microservice-okx-harvester/Dockerfile
      args:
        MODULE: microservice-okx-harvester
    container_name: okx-harvester
    depends_on:
      - redpanda
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      QUARKUS_KAFKA_SCHEMA_REGISTRY_URL: http://redpanda:8081
    networks:
      - redpanda-net
  okx-analyzer:
    build:
      context: .                       # КОРЕНЬ репозитория!
      dockerfile: microservice-okx-analyzer/Dockerfile
      args:
        MODULE: microservice-okx-analyzer
    container_name: okx-analyzer
    depends_on:
      - redpanda
    environment:
      QUARKUS_PROFILE: prod
      QUARKUS_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      QUARKUS_KAFKA_SCHEMA_REGISTRY_URL: http://redpanda:8081
    networks:
      - redpanda-net
  okx-executor:
    build:
      context: .                       # КОРЕНЬ репозитория!
      dockerfile: microservice-okx-executor/Dockerfile
      args:
        MODULE: microservice-okx-executor
    container_name: okx-executor
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      SCHEMA_REGISTRY_URL: http://redpanda:8081
      KAFKA_CONSUMER_GROUP: executor-bot
    depends_on:
      - redpanda
    networks:
      - redpanda-net

networks:
  redpanda-net:
    driver: bridge